version: '3.8'

services:
  twitch-bot-db:
    image: postgres:14.1-alpine
    container_name: twitch-bot-db
    restart: always
    environment:
      POSTGRES_DB: twitch_bot
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  twitch-bot-app:
#     build: ./
    image: mabalda/twitch-chat-bot-twitch-bot-app:latest
    container_name: twitch-bot-app
    environment:
      POSTGRES_DB: twitch_bot
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: twitch-bot-db
      BOT_CLIENT_ID: ${BOT_CLIENT_ID}
      BOT_SECRET: ${BOT_SECRET}
      CHANNEL_NAME: overridetech
      MODERATION_SECRET: ${MODERATION_SECRET}
      MODERATION_CLIENT_ID: ${MODERATION_CLIENT_ID}
      PIXEL_WARS_CLIENT_ID: ${PIXEL_WARS_CLIENT_ID}
      PIXEL_WARS_SECRET: ${PIXEL_WARS_SECRET}
      PIXEL_WARS_REDIRECT_URL: ${PIXEL_WARS_REDIRECT_URL}
    ports:
      - "9000:8080"
