twitch:
  channelName: overridetech
  botClientId: ${BOT_CLIENT_ID}
  botSecret: ${BOT_SECRET}
  moderationSecret: ${MODERATION_SECRET}
  moderationClientId: ${MODERATION_CLIENT_ID}

telegram:
  mentorUsername: Marandyuk_Anatolii

spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:twitch_bot}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
