twitch:
  channelName: ${CHANNEL_NAME:ma_balda}
  botClientId: ${BOT_CLIENT_ID}
  botSecret: ${BOT_SECRET}

telegram:
  mentorUsername: Marandyuk_Anatolii

spring:
  datasource:
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:twitch_bot}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true