twitch:
  channelName: overridetech
  botClientId: ${BOT_CLIENT_ID}
  botSecret: ${BOT_SECRET}
  moderationSecret: ${MODERATION_SECRET}
  moderationClientId: ${MODERATION_CLIENT_ID}
  pixelWarsClientId: ${PIXEL_WARS_CLIENT_ID}
  pixelWarsSecret: ${PIXEL_WARS_SECRET}
  pixelWarsRedirectUrl: ${PIXEL_WARS_REDIRECT_URL:http://localhost:8080/pixel/editor}
  adminName: ${ADMIN}
  adminPassword: ${ADMIN_PASSWORD}


  rewardTitle:
    onePixelReward: pixel(не работает)
    fivePixelReward: 5 пикселей(не работает)
    twentyFivePixelReward: 25 пикселей(не работает)

telegram:
  mentorUsername: Marandyuk_Anatolii

spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:twitch_bot}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

feign:
  client:
    config:
      default:
        loggerLevel: full

pixelWars:
  width: 160
  height: 95
